/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_mcp_settings_mcpSettings_delete_parameter_0$schema = z.object({
  'serverName': z.string().readonly(),
})
const _deepseek_ai_dsh_mcp_settings_mcpSettings_delete_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_mcp_settings_mcpSettings_list_result$schema = z.object({
  'servers': z.array(z.union([z.object({
  'transport': z.literal("stdio").readonly(),
  'command': z.string().readonly(),
  'args': z.array(z.string()).readonly(),
  'cwd': z.string().readonly(),
  'serverName': z.string().readonly(),
  'origin': z.union([z.literal("settings"), z.literal("composition")]).readonly(),
  'enabled': z.boolean().readonly(),
  'fiberPhase': z.union([z.literal(null), z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("loading"), z.literal("unloading")]).readonly(),
  'toolCount': z.number().readonly(),
  'envKeys': z.array(z.string()).readonly(),
  'headerKeys': z.array(z.string()).readonly(),
  'toolCallTimeoutMs': z.number().readonly(),
  'failOnStartupError': z.boolean().readonly(),
}), z.object({
  'transport': z.literal("streamable-http").readonly(),
  'url': z.string().readonly(),
  'serverName': z.string().readonly(),
  'origin': z.union([z.literal("settings"), z.literal("composition")]).readonly(),
  'enabled': z.boolean().readonly(),
  'fiberPhase': z.union([z.literal(null), z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("loading"), z.literal("unloading")]).readonly(),
  'toolCount': z.number().readonly(),
  'envKeys': z.array(z.string()).readonly(),
  'headerKeys': z.array(z.string()).readonly(),
  'toolCallTimeoutMs': z.number().readonly(),
  'failOnStartupError': z.boolean().readonly(),
})])).readonly(),
})
const _deepseek_ai_dsh_mcp_settings_mcpSettings_upsert_parameter_0$schema = z.union([z.object({
  'transport': z.literal("stdio").readonly(),
  'serverName': z.string().readonly(),
  'fromServerName': z.string().readonly().optional(),
  'enabled': z.boolean().readonly().optional(),
  'command': z.string().readonly(),
  'args': z.array(z.string()).readonly().optional(),
  'cwd': z.string().readonly().optional(),
  'env': z.record(z.string(), z.string()).readonly().readonly().optional(),
  'toolCallTimeoutMs': z.number().readonly().optional(),
  'failOnStartupError': z.boolean().readonly().optional(),
}), z.object({
  'transport': z.literal("streamable-http").readonly(),
  'serverName': z.string().readonly(),
  'fromServerName': z.string().readonly().optional(),
  'enabled': z.boolean().readonly().optional(),
  'url': z.string().readonly(),
  'headers': z.record(z.string(), z.string()).readonly().readonly().optional(),
  'toolCallTimeoutMs': z.number().readonly().optional(),
  'failOnStartupError': z.boolean().readonly().optional(),
})])
const _deepseek_ai_dsh_mcp_settings_mcpSettings_upsert_result$schema = z.object({
  'ok': z.literal(true).readonly(),
})

export const TYPERT = {
  package: 'dsh-plus',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-plus#mcpSettings/delete',
      service: 'mcpSettings',
      namespace: 'mcpSettings',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plus/types#McpServerRemoveRequest',
            schema: _deepseek_ai_dsh_mcp_settings_mcpSettings_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plus/types#McpSettingsMutationResult',
        schema: _deepseek_ai_dsh_mcp_settings_mcpSettings_delete_result$schema,
      },
      sourceLocation: {"file":"packages/mcp/mcp-settings/src/index.ts","line":172,"column":3},
    },
    {
      id: 'dsh-plus#mcpSettings/list',
      service: 'mcpSettings',
      namespace: 'mcpSettings',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plus/types#McpSettingsSnapshot',
        schema: _deepseek_ai_dsh_mcp_settings_mcpSettings_list_result$schema,
      },
      sourceLocation: {"file":"packages/mcp/mcp-settings/src/index.ts","line":131,"column":3},
    },
    {
      id: 'dsh-plus#mcpSettings/upsert',
      service: 'mcpSettings',
      namespace: 'mcpSettings',
      method: 'upsert',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plus/types#McpServerUpsertRequest',
            schema: _deepseek_ai_dsh_mcp_settings_mcpSettings_upsert_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plus/types#McpSettingsMutationResult',
        schema: _deepseek_ai_dsh_mcp_settings_mcpSettings_upsert_result$schema,
      },
      sourceLocation: {"file":"packages/mcp/mcp-settings/src/index.ts","line":143,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host Remote that stores UI-managed MCP servers and mounts mcp-client children for enabled Settings-origin records.",
        "summary": "Host Remote that stores UI-managed MCP servers and mounts mcp-client children for enabled Settings-origin records.",
        "tags": [],
        "jsDoc": "/**\n * Host Remote that stores UI-managed MCP servers and mounts mcp-client\n * children for enabled Settings-origin records.\n */",
        "key": "mcpSettings",
        "exportName": "McpSettingsGateway",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(): Promise<McpSettingsSnapshot>",
            "summary": "Project Settings-owned records and composition-owned mcp-client rows.",
            "jsDoc": "/**\n * Project Settings-owned records and composition-owned mcp-client rows.\n * Secret maps contribute keys only. Each row includes the live fiber phase\n * and the number of globally registered tools in that server's namespace.\n * @returns the current catalog snapshot.\n */"
          },
          {
            "kind": "method",
            "name": "upsert",
            "signature": "@Remote('upsert') upsert(request: McpServerUpsertRequest): Promise<McpSettingsMutationResult>",
            "summary": "Create or replace one Settings-owned MCP server and remount its fiber.",
            "jsDoc": "/**\n * Create or replace one Settings-owned MCP server and remount its fiber.\n * A distinct `fromServerName` renames that Settings row in place, keeps\n * omitted env/headers, and remounts tools under the new namespace.\n * @param request - create, replace, or rename payload.\n * @returns acknowledgement after the document commit.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') delete(request: McpServerRemoveRequest): Promise<McpSettingsMutationResult>",
            "summary": "Delete one Settings-owned MCP server and dispose its fiber.",
            "jsDoc": "/**\n * Delete one Settings-owned MCP server and dispose its fiber.\n * @param request - namespace to delete.\n * @returns acknowledgement after the document commit.\n */"
          }
        ],
        "types": [
          {
            "name": "McpHttpServerView",
            "declaration": "export interface McpHttpServerView extends McpServerViewBase {\n    readonly transport: 'streamable-http';\n    readonly url: string;\n}"
          },
          {
            "name": "McpHttpUpsertRequest",
            "declaration": "export interface McpHttpUpsertRequest {\n    readonly transport: 'streamable-http';\n    readonly serverName: string;\n    readonly fromServerName?: string;\n    readonly enabled?: boolean;\n    readonly url: string;\n    readonly headers?: Readonly<Record<string, string>>;\n    readonly toolCallTimeoutMs?: number;\n    readonly failOnStartupError?: boolean;\n}"
          },
          {
            "name": "McpServerFiberPhase",
            "declaration": "export type McpServerFiberPhase = 'pending' | 'loading' | 'active' | 'failed' | 'unloading' | null;"
          },
          {
            "name": "McpServerOrigin",
            "declaration": "export type McpServerOrigin = 'settings' | 'composition';"
          },
          {
            "name": "McpServerRemoveRequest",
            "declaration": "export interface McpServerRemoveRequest {\n    readonly serverName: string;\n}"
          },
          {
            "name": "McpServerTransport",
            "declaration": "export type McpServerTransport = 'stdio' | 'streamable-http';"
          },
          {
            "name": "McpServerUpsertRequest",
            "declaration": "export type McpServerUpsertRequest = McpStdioUpsertRequest | McpHttpUpsertRequest;"
          },
          {
            "name": "McpServerView",
            "declaration": "export type McpServerView = McpStdioServerView | McpHttpServerView;"
          },
          {
            "name": "McpServerViewBase",
            "declaration": "export interface McpServerViewBase {\n    readonly serverName: string;\n    readonly origin: McpServerOrigin;\n    readonly enabled: boolean;\n    readonly fiberPhase: McpServerFiberPhase;\n    readonly toolCount: number;\n    readonly transport: McpServerTransport;\n    readonly envKeys: readonly string[];\n    readonly headerKeys: readonly string[];\n    readonly toolCallTimeoutMs: number;\n    readonly failOnStartupError: boolean;\n}"
          },
          {
            "name": "McpSettingsMutationResult",
            "declaration": "export interface McpSettingsMutationResult {\n    readonly ok: true;\n}"
          },
          {
            "name": "McpSettingsSnapshot",
            "declaration": "export interface McpSettingsSnapshot {\n    readonly servers: readonly McpServerView[];\n}"
          },
          {
            "name": "McpStdioServerView",
            "declaration": "export interface McpStdioServerView extends McpServerViewBase {\n    readonly transport: 'stdio';\n    readonly command: string;\n    readonly args: readonly string[];\n    readonly cwd: string;\n}"
          },
          {
            "name": "McpStdioUpsertRequest",
            "declaration": "export interface McpStdioUpsertRequest {\n    readonly transport: 'stdio';\n    readonly serverName: string;\n    readonly fromServerName?: string;\n    readonly enabled?: boolean;\n    readonly command: string;\n    readonly args?: readonly string[];\n    readonly cwd?: string;\n    readonly env?: Readonly<Record<string, string>>;\n    readonly toolCallTimeoutMs?: number;\n    readonly failOnStartupError?: boolean;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
